# Generated by Django 5.0.4 on 2024-04-29 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_shopcart_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='order_num',
        ),
    ]
