# Generated by Django 5.0.4 on 2024-04-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_shopcart_order_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='order_num',
            field=models.BigIntegerField(default=1),
        ),
    ]
