# Generated by Django 5.0.4 on 2024-04-30 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_shopcart_order_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopcart',
            old_name='order_num',
            new_name='order_no',
        ),
    ]
