# Generated by Django 5.0.4 on 2024-04-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_order_num_shopcart_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='order_no',
            field=models.CharField(default='', max_length=50),
        ),
    ]
